// Players still in the game, ordered by kill count.
// When someone is eliminated: remove from here, add to TRIBUTES below.
const SURVIVORS = [
  { name: "Zane",      kills: 3, image: "pics/Zane.png" },
  { name: "Christina", kills: 3, image: "pics/Christina.png" },
  { name: "Isaiah",    kills: 2, image: "pics/Isaiah.png" },
  { name: "Sam",       kills: 2, image: "pics/Sam_Dawson_Shors.png" },
  { name: "Breno",     kills: 1, image: "pics/Breno.png" },
  { name: "Maya",      kills: 1, image: "pics/Maya.png" },
  { name: "Agam",      kills: 1, image: "pics/Agam.png" },
  { name: "Angela",    kills: 1, image: "pics/Angela.png" },
  { name: "Ameya",     kills: 0, image: "pics/Ameya.png" },
  { name: "Aniket",    kills: 1, image: "pics/Aniket.png" },
  { name: "Laith",     kills: 1, image: "pics/Laith.png" },
  { name: "Valeria",   kills: 0, image: "pics/Valeria.png" },
  { name: "Ella",      kills: 0, image: "pics/Ella.png" },
  { name: "Sameeh",    kills: 0, image: "pics/Sameeh.png" },
  { name: "Ryan",      kills: 0, image: "pics/Ryan.png" },
  { name: "Isaac",     kills: 0, image: "pics/Isaac.png" },
  { name: "Kate",      kills: 0, image: "pics/Kate.png" },
  { name: "Jasmine",   kills: 0, image: "pics/Jasmine.png" },
  { name: "Casey",     kills: 0, image: "pics/Casey.png" },
  { name: "Aditri",   kills: 0, image: "pics/Aditri.png" },
  { name: "Ashley",   kills: 0, image: "pics/Ashley.png" },
];

// Tributes in chronological elimination order.
// To add a new fallen: append an entry and move recent:true to them.
// Fields method and location are optional — set to null to omit.
const TRIBUTES = [

  // ── May 18 ──────────────────────────────────────────────────────
  {
    name: "Armando",
    image: "pics/Armando.png",
    noPhoto: false,
    recent: false,
    killedBy: "that bastard Niall",
    date: "May 18",
    time: "11:58 AM",
    method: null,
    location: null,
  },
  {
    name: "Alyssa Jones",
    image: "pics/Alyssa.png",
    noPhoto: false,
    recent: false,
    killedBy: "Ben",
    date: "May 18",
    time: "1:33 PM",
    method: null,
    location: null,
  },
  {
    name: "Emilio Rueda-Quevedo",
    image: "pics/Emilio.png",
    noPhoto: false,
    recent: false,
    killedBy: "Luke",
    date: "May 18",
    time: "1:38 PM",
    method: null,
    location: null,
  },
  {
    name: "Riya Ranjan",
    image: "pics/Riya.png",
    noPhoto: false,
    recent: false,
    killedBy: "the greatest to ever do it",
    date: "May 18",
    time: "3:07 PM",
    method: null,
    location: null,
  },
  {
    name: "Allie Montoya",
    image: "pics/Allie.png",
    noPhoto: false,
    recent: false,
    killedBy: "Isaiah",
    date: "May 18",
    time: "7:03 PM",
    method: null,
    location: null,
  },
  {
    name: "Fionn",
    image: "pics/Fionn.jpeg",
    noPhoto: false,
    recent: false,
    killedBy: "Sarah",
    date: "May 18",
    time: "7:03 PM",
    method: null,
    location: null,
  },
  {
    name: "Joelle",
    image: "pics/Joelle.png",
    noPhoto: false,
    recent: false,
    killedBy: "Naoise",
    date: "May 18",
    time: "7:04 PM",
    method: null,
    location: null,
  },
  {
    name: "Naoise",
    image: "pics/Naoise.jpeg",
    noPhoto: false,
    recent: false,
    killedBy: "Paolo",
    date: "May 18",
    time: "7:08 PM",
    method: null,
    location: null,
  },
  {
    name: "Zubin Carvalho",
    image: "pics/Zubin.png",
    noPhoto: false,
    recent: false,
    killedBy: "Paolo",
    date: "May 18",
    time: "7:08 PM",
    method: null,
    location: null,
  },
  {
    name: "Ana",
    image: "pics/Anna.png",  // file is Anna.png — rename to Ana.png if wrong person
    noPhoto: false,
    recent: false,
    killedBy: "Christina",
    date: "May 18",
    time: "7:49 PM",
    method: null,
    location: null,
  },
  {
    name: "Jaxon Gonzales",
    image: "pics/Jaxon.png",
    noPhoto: false,
    recent: false,
    killedBy: "Tate",
    date: "May 18",
    time: "8:42 PM",
    method: null,
    location: null,
  },
  {
    name: "Sarah Baldeon",
    image: "pics/Sarah.png",
    noPhoto: false,
    recent: false,
    killedBy: "Cees",
    date: "May 18",
    time: "9:22 PM",
    method: null,
    location: null,
  },
  {
    name: "Andrew Park",
    image: "pics/Andrew.png",
    noPhoto: false,
    recent: false,
    killedBy: "Amanda",
    date: "May 18",
    time: "9:24 PM",
    method: null,
    location: null,
  },
  {
    name: "Jalen Hunter",
    image: "pics/Jalen.png",
    noPhoto: false,
    recent: false,
    killedBy: "Tate",
    date: "May 18",
    time: "10:29 PM",
    method: null,
    location: null,
  },
  {
    name: "Amanda Altarejos",
    image: "pics/Amanda.png",
    noPhoto: false,
    recent: false,
    killedBy: "Zane",
    date: "May 18",
    time: "11:29 PM",
    method: null,
    location: null,
  },
  {
    name: "Carlos Pardo",
    image: "pics/Carlos.png",
    noPhoto: false,
    recent: false,
    killedBy: "Zane",
    date: "May 18",
    time: "11:29 PM",
    method: null,
    location: null,
  },
  {
    name: "Ruhee Nemawarkar",
    image: "pics/Ruhee.png",
    noPhoto: false,
    recent: false,
    killedBy: "Zane",
    date: "May 18",
    time: "Late night",
    method: null,
    location: null,
  },

  // ── May 19 ──────────────────────────────────────────────────────
  {
    name: "Luke Zhao",
    image: "pics/Luke.png",
    noPhoto: false,
    recent: false,
    killedBy: "Sam",
    date: "May 19",
    time: "1:06 PM",
    method: null,
    location: null,
  },
  {
    name: "Paolo Reitz",
    image: "pics/Paolo.png",
    noPhoto: false,
    recent: false,
    killedBy: null,
    date: "May 19",
    time: "1:42 PM",
    method: null,
    location: null,
  },
  {
    name: "Julia Segal",
    image: "pics/Julia.png",
    noPhoto: false,
    recent: false,
    killedBy: "Agam",
    date: "May 19",
    time: "7:17 PM",
    method: null,
    location: null,
  },

  // ── May 20 ──────────────────────────────────────────────────────
  {
    name: "Cees Armstrong",
    image: "pics/Cees.png",
    noPhoto: false,
    recent: false,
    killedBy: "Maya",
    date: "May 20",
    time: "1:07 PM",
    method: null,
    location: null,
  },
  {
    name: "Stephanie Boczek",
    image: "pics/Stephanie.png",
    noPhoto: false,
    recent: false,
    killedBy: "Sam",
    date: "May 20",
    time: "9:36 PM",
    method: null,
    location: null,
  },
  {
    name: "Tate Sgaraglino",
    image: "pics/Tate.png",
    noPhoto: false,
    recent: false,
    killedBy: "Breno",
    date: "May 20",
    time: "9:49 PM",
    method: null,
    location: null,
  },
  {
    name: "Aarzoo Aggarwal",
    image: "pics/Aarzoo.png",
    noPhoto: false,
    recent: false,
    killedBy: "Niall",
    date: "May 20",
    time: "11:16 PM",
    method: null,
    location: null,
  },
  {
    name: "Ben Kinder",
    image: "pics/Ben.png",
    noPhoto: false,
    recent: false,
    killedBy: "Isaiah",
    date: "May 20",
    time: "11:23 PM",
    method: null,
    location: null,
  },

  // ── May 21 ──────────────────────────────────────────────────────
  {
    name: "Jenin",
    image: "pics/Jenin.png",
    noPhoto: false,
    recent: false,
    killedBy: "Laith",
    date: "May 21",
    time: "11:52 AM",
    method: null,
    location: null,
  },
  {
    name: "Niall",
    image: "pics/Niall.png",
    noPhoto: false,
    recent: false,
    killedBy: "Christina",
    date: "May 21",
    time: "1:04 PM",
    method: null,
    location: null,
  },
  {
    name: "Keira",
    image: "pics/Keira.png",
    noPhoto: false,
    recent: false,
    killedBy: "Christina",
    date: "May 21",
    time: "1:25 PM",
    method: null,
    location: null,
  },
  {
    name: "Lili",
    image: "pics/Lili.png",
    noPhoto: false,
    recent: true,
    killedBy: "Aniket",
    date: "May 21",
    time: "1:44 PM",
    method: null,
    location: null,
  },

];
